#!/bin/bash
#checkstatus  
URL=$1
curl=`curl -I $URL 2>/dev/null | head -n 1`
redirect=`curl -I -Ls -o /dev/null -w %{url_effective} $URL`
location=`curl -I $redirect 2>/dev/null | head -n 1`
chain=`curl --head --silent --location --output /dev/null --write-out "It took %{num_redirects} redirect/redirects to get %{url_effective}\n" $URL`
#grabbing the 301/302 redirect to know which curl to run if 301/302 run $location if its not run $curl 
   if  [[ `echo $curl | grep -E 301\|302` ]]; 
   then 
      echo $location
   else 
      echo $curl
   fi
#the while loop follows the redirect/ show all of the redirects
    while [ -n "${URL}" ]
do
    echo $URL
    URL=$(curl -sw "\n\n%{redirect_url}" "${URL}" | tail -n 1)
done
#when you add the string trace it will show you the write out of how many redirects it took to get to the final destination 
   if [[ $2 == *"trace"* ]]; 
   then
      echo $chain
   fi   
